version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    env_file:
      - .env.pg

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./server:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - app
    env_file:
      - .env.node
    command: /bin/bash -c "npm i && npm run start:prod"
    ports:
      - "3000:3000"

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    volumes:
      - ./client:/usr/src/app/
    depends_on:
      - node
    networks:
      - app
    links:
      - node
    command: /bin/bash -c "npm i && npm run start:prod"
    ports:
      - 8080:8080

networks:
  app:
