version: '2'
services:
  mongodb:
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    env_file: '.env.mongodb'
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./src/:/usr/src/app/
      - /usr/src/node_modules
    links:
      - "mongodb"
    env_file:
      - ".env.mongodb"
      - ".env.node"
    command: /bin/bash -c "npm i && npm start"
    ports:
      - "3000"
