export const GET_INTERNSHIP_LIST = 'GET_INTERNSHIP_LIST';
export const GET_INTERNSHIP_LIST_REQUESTING = 'GET_INTERNSHIP_LIST_REQUESTING';
export const GET_INTERNSHIP_LIST_SUCCESS = 'GET_INTERNSHIP_LIST_SUCCESS';
export const GET_INTERNSHIP_LIST_FAIL = 'GET_INTERNSHIP_LIST_FAIL';

export const GET_INTERNSHIP_DETAILS = 'GET_INTERNSHIP_DETAILS';
export const GET_INTERNSHIP_DETAILS_REQUESTING = 'GET_INTERNSHIP_DETAILS_REQUESTING';
export const GET_INTERNSHIP_DETAILS_SUCCESS = 'GET_INTERNSHIP_DETAILS_SUCCESS';
export const GET_INTERNSHIP_DETAILS_FAIL = 'GET_INTERNSHIP_DETAILS_FAIL';
